PMM-6585 Always expose mongodb_up metric
percona/mongodb_exporter pull request #207
Opened 2020-09-09 20:24 UTC by percona-csalguero

Created a new exporter named `generalCollector` where we can put any metric that's not related to any specific collector.
Also, this collector cannot be disabled so, the `mongodb_up` metric is going to be always exposed.
Fixed error from merging connection strategy and topology labels that made tests to fail.

2020-09-10 09:12 UTC, askomorokhov reviewed
Overall looks good. Just two comments

2020-09-10 09:12 UTC, askomorokhov commented on exporter/exporter.go
> +	ti, err := newTopologyInfo(context.TODO(), client)
And as an idea.
If we are gathering topology on each request now, maybe we can simplify topologyInfo a few methods and simply pass labels to collectors (but not a whole instance of topologyInfo)?

2020-09-10 09:28 UTC, AlekSi commented on exporter/exporter.go
> +	ti, err := newTopologyInfo(context.TODO(), client)
Yeah, ctx is a must there

2020-09-10 09:28 UTC, AlekSi commented on exporter/exporter.go
> +			topologyInfo:   ti,
Can those collectors handle `topologyInfo == nil`?

2020-09-10 09:28 UTC, AlekSi commented on exporter/general_collector_test.go
> +	// TODO: use NewPedanticRegistry when mongodb_exporter code fulfils its requirements (https://jira.percona.com/browse/PMM-6630).
I _think_ there we should be able to use `NewPedanticRegistry` without problems – we always return one consistent metric

2020-09-10 09:28 UTC, AlekSi commented on internal/tu/testutils.go
> +		client.Disconnect(ctx) //nolint
Let's be specific if we can. I guess `//nolint:errcheck` should work

2020-09-10 09:28 UTC, AlekSi commented on internal/tu/testutils.go
> +		// it might be already disconnected.
👍

2020-09-10 14:43 UTC, askomorokhov approved these changes

2020-09-10 14:43 UTC, askomorokhov commented on exporter/exporter.go
> +		if e.topologyInfo, err = newTopologyInfo(ctx, client); err != nil {
e.topologyInfo` can be local variable as we not use it outside of the current method.
In this case, `e.lock` will obsolete as well.

2020-09-11 11:26 UTC, BupycHuk requested changes
please revert all changes related to topologyInfo

2020-09-11 14:00 UTC, percona-csalguero commented
why?

2020-09-11 14:48 UTC, closed without merging

2020-09-11 14:48 UTC, percona-csalguero commented
Closing in favor of https://github.com/percona/mongodb_exporter/pull/208