Udpate Readme with discord link
percona/mongodb_exporter pull request #275
Opened 2021-05-18 15:48 UTC by denisok

2021-05-21 22:46 UTC, percona-csalguero requested changes
The link is invalid. 
When you click on it it says: `this link may be expired or you might not have permission to join`

2021-05-25 11:35 UTC, percona-csalguero approved these changes

2021-05-25 11:36 UTC, percona-csalguero commented
Now it works. Thanks

2021-05-25 12:16 UTC, askomorokhov approved these changes

2021-05-25 12:17 UTC, merged