Create reference document
percona/mongodb_exporter pull request #484
Opened 2022-05-04 09:27 UTC by ShashankSinha252

[PMM-1458](https://jira.percona.com/browse/PMM-1458) : Update documentation for MongoDB exporter

2022-05-04 09:31 UTC, denisok approved these changes

2022-05-20 08:07 UTC, rasika-chivate requested changes

2022-05-20 08:07 UTC, rasika-chivate commented on README.md
> +Check out [Reference Guide](REFERENCE.md) for details on using exporter.
```suggestion
See the [Reference Guide](REFERENCE.md) for details on using the exporter.
```

2022-05-20 08:07 UTC, rasika-chivate commented on README.md
> +Please read [Contribution Guide](CONTRIBUTING.md).
```suggestion
 Refer to the [Contribution Guide](CONTRIBUTING.md).
```

2022-05-20 09:15 UTC, ShashankSinha252 commented on README.md
> +Please read [Contribution Guide](CONTRIBUTING.md).
Done

2022-05-20 09:15 UTC, ShashankSinha252 commented on README.md
> +Check out [Reference Guide](REFERENCE.md) for details on using exporter.
Done

2022-05-21 06:37 UTC, ShashankSinha252 commented
@rasika-chivate please review PR again.

2022-05-23 07:18 UTC, rasika-chivate approved these changes

2022-05-23 07:20 UTC, merged