Support Prometheus multiple targets
percona/mongodb_exporter pull request #493
Opened 2022-05-16 10:16 UTC by twink7e

### commit: 6c2f04d888b696bcc9e9199d5d46ea4e25a4e793 : Support Prometheus multiple targets

example for  prometheus multiple targets scrape-config
```yaml
- job_name: "mongodb-test"
  static_configs:
      - targets:
        # - mongodb://cdp-user:2NML9O3xdaHq1@192.168.50.1:28018,192.168.60.1:28018/admin
        - mongodb://user:pass@192.168.1.91:27017/admin
        - mongodb://user:pass@192.168.1.92:27017/admin
  metrics_path: /scrape
  scrape_timeout: 30s
  relabel_configs:
      # add cluster name
      - source_labels: [cluster_name]
        replacement: "mongodb-test"
        target_label: "cluster_name"
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        regex: "(?:mongodb://)(?:.*?:.*?@)(.+?)(/.+)?"
        replacement: "${1}"
        target_label: instance
      - target_label: __address__
        replacement: "mongo-exporter:9216"
      # here set to collect what kind of metrics of mongodb.
      - source_labels: [__param_collect]
        replacement: "diagnosticdata"
        target_label: __param_collect
```

### commit: 5398ce4fad1e0cee409fb5364396583c74644072   change go version to 1.18
Upgrade GO to 1.18 is to implement `MongoClientLRUPool` . 
`MongoClientLRUPool`  implements LRU and is responsible for maintaining MongoClient. 

---

- [x ] Tests passed.
- [x ] Fix conflicts with target branch.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

Once all checks pass and the code is ready for review, please add `pmm-review-exporters` team as the reviewer. That would assign people from the review team automatically. Report any issues on our [Forum](https://forums.percona.com) or [Discord](https://per.co.na/discord).

2022-05-23 12:17 UTC, percona-csalguero requested changes

2022-05-23 12:22 UTC, tshcherban approved these changes

2022-05-31 09:32 UTC, tshcherban approved these changes

2022-06-03 08:24 UTC, JiriCtvrtka approved these changes
Please resolve conflicts here.

2022-06-30 02:19 UTC, closed without merging