PMM-9586 Added support for histogram metrics
percona/mongodb_exporter pull request #531
Opened 2022-07-21 18:01 UTC by percona-csalguero

- Added support for histogram metrics
- Upgraded all dependencies.

[PMM-9568](https://jira.percona.com/browse/PMM-9568)

2022-07-21 20:12 UTC, BupycHuk requested changes

2022-07-21 20:12 UTC, BupycHuk commented on exporter/metrics.go
> +	//         }
I checked some histogram examples and I found out that each primitive.M contains two fields: some key and `count`. So I think that the key should be used as a label and `count` as a value.

2022-07-21 20:12 UTC, BupycHuk commented on exporter/metrics_test.go
> +	t.Run("Valid Histogram", func(t *testing.T) {
```suggestion
	t.Run("Invalid Histogram", func(t *testing.T) {
```

2022-07-26 12:03 UTC, tshcherban approved these changes

2022-07-28 14:55 UTC, percona-csalguero commented
@BupycHuk
I've updated histograms. Now we have labels for buckets:
```
# TYPE mongodb_ss_wt_perf untyped
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system read latency histogram (bucket 1) - 10-49ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system read latency histogram (bucket 2) - 50-99ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system read latency histogram (bucket 3) - 100-249ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system read latency histogram (bucket 4) - 250-499ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system read latency histogram (bucket 5) - 500-999ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system read latency histogram (bucket 6) - 1000ms+",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system write latency histogram (bucket 1) - 10-49ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system write latency histogram (bucket 2) - 50-99ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system write latency histogram (bucket 3) - 100-249ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system write latency histogram (bucket 4) - 250-499ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system write latency histogram (bucket 5) - 500-999ms",rs_state="0"} 0
mongodb_ss_wt_perf{cl_id="",cl_role="",perf_bucket="file system write latency histogram (bucket 6) - 1000ms+",rs_state="0"} 0
```

2025-05-05 02:14 UTC, closed without merging

2025-05-12 13:22 UTC, Ray-Barker commented
Can this be reopened or is there a new implementation may be?