added respective .go files for  setup.sh and init-shard.sh
percona/mongodb_exporter pull request #727
Opened 2023-10-10 03:30 UTC by RISHIKESHk07

[PMM-XXXX](https://jira.percona.com/browse/PMM-XXXX) (optional, if ticket reported)
 
- [ ] Links to other linked pull requests (optional).

---

- [x] Tests passed.
- [ ] Fix conflicts with target branch.
- [ ] Update jira ticket description if needed.
- [ ] Attach screenshots/console output to confirm new behavior to jira ticket, if applicable.

Once all checks pass and the code is ready for review, please add `pmm-review-exporters` team as the reviewer. That would assign people from the review team automatically. Report any issues on our [Forum](https://forums.percona.com).

2023-10-10 05:56 UTC, JiriCtvrtka commented on docker/scripts/init-shard.go
> +	mongodb11Resolved, _ := resolveHost(mongo11)
Since we returning error from resolveHost it would be nice to print it.

2023-10-10 05:57 UTC, JiriCtvrtka commented on docker/scripts/setup.go
> +	switch os.Args[1] {
Maybe check if os args with index 1 is available.

2023-10-10 05:57 UTC, JiriCtvrtka approved these changes
LGTM, just two small comments.

2023-10-10 09:03 UTC, BupycHuk requested changes
Please address comments from linter and fix tests

2023-10-12 11:21 UTC, RISHIKESHk07 commented
@BupycHuk any additional changes ?

2024-12-05 14:35 UTC, closed without merging